name: Build

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: ${{ matrix.rust }}
      - name: Build release
        run: cargo build --release
      - name: Archive release
        uses: actions/upload-artifact@v2
        with:
          name: release-${{ matrix.os }}
          path: target/release/rgh